services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: "clonetabnews"
      POSTGRES_PASSWORD: "clonetabnews"
      POSTGRES_DB: "clonetabnews"
    ports:
      - "5432:5432"
